language: node_js
sudo: false
node_js:
- '0.10'
- '0.11'
- '0.12'
before_script:
- npm install mocha
script:
- node_modules/.bin/mocha
before_deploy:
- npm install json
- node_modules/.bin/json -E "this.version='$TRAVIS_TAG'" -f package.json -I
deploy:
  provider: npm
  email: JanS@DracoBlue.de
  api_key:
    secure: mzLrVmJq4Bd3z5D6rWvsz5mWzKGDCgWa1R/P0fJjJx8lT1sM8iwn6qAWEEOldPbrEUp7v8UZH9ILwhuUE3ivT2WTtNktZbwSsNMaSserfrsFkg8FFv5tbuH3pUy/LP5FjUwPeV0e82zrk9ClwZhgWKMfPJntYzugWhjSUyG5/V4=
  on:
    tags: true
    repo: DracoBlue/jsb
    all_branches: true
    node: 0.12
